version: "3"
services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ravindu_sit722_postgresql_qb0e_user:eOCIlslpkK1Kvmx9avgwMZOeBRMvdA0b@dpg-crp6d55ds78s73d4vnpg-a.oregon-postgres.render.com/ravindu_sit722_postgresql_qb0e
    depends_on:
      - inventory_management

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://ravindu_sit722_postgresql_qb0e_user:eOCIlslpkK1Kvmx9avgwMZOeBRMvdA0b@dpg-crp6d55ds78s73d4vnpg-a.oregon-postgres.render.com/ravindu_sit722_postgresql_qb0e
